# Summary

Create text files from previously crawls.

In [21]:
import os, sys

import pandas as pd

utils_path = "../../interface/utils"
sys.path.insert(0, utils_path)
from authentication import ApiAuthentication
import gcp_tools as gct

# Set environment variables
dotenv_path = "../../data/environment"
api_configs = ApiAuthentication(dotenv_path=dotenv_path)
api_configs.set_environ_variables()

# Initialize Vertex AI API once per session
# vertexai.init(project=os.environ["GOOGLE_CLOUD_PROJECT"],
#               location=os.environ["GOOGLE_CLOUD_LOCATION"],
#               staging_bucket=os.environ["STAGING_BUCKET"])

In [22]:
gcs_bucket_name = "ccc-crawl_data_xb"
bcontents = gct.gcp_list_bucket(gcp_project_id=os.environ["GOOGLE_CLOUD_PROJECT"],
                                gcs_bucket_name=gcs_bucket_name,
                                path="")

In [25]:

cfiles = []
for bc in bcontents:
    fp = os.path.split(bc)
    ps = fp[0].split("/")

    source = ps[1] if len(ps) > 1 else ""
    file_name = fp[1] if fp[1].find(".csv") >= 0 else ""

    if len(file_name) > 0:
        cfiles.append(dict(source=source,
                           file_name=file_name,
                           path=fp[0]))

dfc = pd.DataFrame(data=cfiles)

dfc


    # if bc["name"].endswith(".csv"):
    #     print(bc["name"])
    #     gct.gcp_download_blob(gcp_project_id=os.environ["GOOGLE_CLOUD_PROJECT"],)

,source,file_name,path
0,aacc,wwwaaccncheedu_2025May01_1.csv,crawl_data/aacc/webpages_pdfs
1,aacc,wwwaaccncheedu_2025May01_2.csv,crawl_data/aacc/webpages_pdfs
2,aacc,wwwaaccncheedu_2025May01_3.csv,crawl_data/aacc/webpages_pdfs
3,aacc,wwwaaccncheedu_2025May01_4.csv,crawl_data/aacc/webpages_pdfs
4,aacc,wwwaaccncheedu_2025May01_5.csv,crawl_data/aacc/webpages_pdfs
...,...,...,...
81,nsc,nscresearchcenterorg_2025May01_3.csv,crawl_data/nsc/webpages_pdfs
82,wikipedia,enwikipediaorg_2025May01_1.csv,crawl_data/wikipedia/webpages_pdfs
83,wikipedia,enwikipediaorg_2025May01_2.csv,crawl_data/wikipedia/webpages_pdfs
84,wikipedia,enwikipediaorg_2025May01_3.csv,crawl_data/wikipedia/webpages_pdfs
85,wikipedia,enwikipediaorg_2025May01_4.csv,crawl_data/wikipedia/webpages_pdfs

In [50]:

mask = dfc["source"] == "aacc"
mask = dfc["source"] == "wikipedia"
mask = dfc["source"] == "ipeds"


dfs = []
for idx in dfc[mask].index[:1]:
    print(dfc.loc[idx, "file_name"])
    df = gct.read_csv_file_into_pandas(gcs_project_id=os.environ["GOOGLE_CLOUD_PROJECT"],
                                       gcs_bucket_name=gcs_bucket_name,
                                       gcs_directory=dfc.loc[idx, "path"],
                                       file_name=dfc.loc[idx, "file_name"],
                                       exact=False)
    dfs.append(df)

df = pd.concat(dfs)

df = df.reset_index(drop=True)

prep_2025Apr29_c2023_a.csv

In [51]:
df

,Unnamed: 0,UNITID,CIPCODE,MAJORNUM,AWLEVEL,XCTOTALT,CTOTALT,XCTOTALM,CTOTALM,XCTOTALW,...,CUNKNM,XCUNKNW,CUNKNW,XCNRALT,CNRALT,XCNRALM,CNRALM,XCNRALW,CNRALW,college_name
0,0,108667,5.0200,1,3,R,0,R,0,Z,...,0,Z,0,Z,0,Z,0,Z,0,COLLEGE OF ALAMEDA
1,1,108667,9.0101,1,3,R,2,R,2,Z,...,0,Z,0,Z,0,Z,0,Z,0,COLLEGE OF ALAMEDA
2,2,108667,11.0103,1,3,R,1,R,1,Z,...,0,Z,0,Z,0,Z,0,Z,0,COLLEGE OF ALAMEDA
3,3,108667,11.0103,1,20,R,0,R,0,Z,...,0,Z,0,Z,0,Z,0,Z,0,COLLEGE OF ALAMEDA
4,4,108667,11.0103,1,21,R,1,R,1,Z,...,0,Z,0,Z,0,Z,0,Z,0,COLLEGE OF ALAMEDA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14314,14314,489201,54.0101,1,4,R,0,R,0,Z,...,0,Z,0,R,0,R,0,Z,0,CLOVIS COMMUNITY COLLEGE
14315,14315,489201,99.0000,1,2,R,0,R,0,Z,...,0,Z,0,R,0,R,0,Z,0,CLOVIS COMMUNITY COLLEGE
14316,14316,489201,99.0000,1,3,R,1441,R,529,R,...,2,R,10,R,0,R,0,Z,0,CLOVIS COMMUNITY COLLEGE
14317,14317,489201,99.0000,1,4,R,0,R,0,Z,...,0,Z,0,R,0,R,0,Z,0,CLOVIS COMMUNITY COLLEGE
14318,14318,489201,99.0000,1,21,R,904,R,324,R,...,0,R,4,R,0,R,0,Z,0,CLOVIS COMMUNITY COLLEGE

In [42]:
df.loc[2, "ptag_text"]

'Orange Coast College (OCC) is a public community college in Costa Mesa in Orange County, California. It was founded in 1947, with its first classes opening in the fall of 1948. It provides Associate of Art and Associate of Science degrees, certificates of achievement, and lower-division classes transferable to other colleges and universities. The college enrolls approximately 24,000 undergraduate students. In terms of population size, Orange Coast College is the third-largest college in Orange County. Orange Coast College was formed after local voters passed a measure in the January 1947 election to establish a new junior college on a 243-acre (0.98 km2) site, secured from the War Assets Administration in Washington, D.C., and part of the 1,300-acre (5.3 km2) deactivated Santa Ana Army Air Base. The first official District board of trustees hired the college\'s founding president and district superintendent, Basil Hyrum Peterson, on July 28, 1947. Construction of campus classrooms and facilities began when Peterson hired Fran Albers as the college\'s carpenter in February 1948. Albers\' crew of 35 workers (mostly Coast football players paid 60 cents an hour) turned an Army movie theatre into an auditorium and concert hall; a service club into a 500-seat gymnasium; an Army chapel into a facility for theatre productions and student/staff weddings; a military storage building into a library; an Army PX into a student center; a battalion headquarters building into an administration building; and several cadet barracks into student dormitories and married student and faculty housing. The first campus building phase occurred in the early 1950s when renowned architect Richard Neutra was brought in to re-design the campus. Leaving many of the original buildings intact, Neutra added several modernist structures including the strikingly minimalist Campus Theater and two large lecture halls. These were laid out on a 45-degree angle to the city street grid, in much the same manner as The Parkinsons\' layout of USC. The second and largest building phase occurred in the 1970s when local architect William Blurock was hired to replace many of the original Army buildings with structures more suitable for educational purposes. In December 2002, Rabbit Island, a 38-acre (150,000 m2) island located in the North Gulf Islands of the Georgia Strait 50 miles (80 km) west of the city of Vancouver in British Columbia, Canada, was donated to the Orange Coast College Foundation. Since then the OCC Foundation, using funds designated for the Orange Coast College School of Sailing & Seamanship, has refurbished the facilities on the island, made significant capital improvements, and has helped fund the use of the island as a field station to teach summer classes in Island Ecology, Biological Diversity, Vertebrate Biology, Intertidal Ecology, kayaking, and photography. It is now referred to as "Wheeler Station" at Rabbit Island (in honor of the donor, Henry Wheeler). OCC marine science and biology instructors have used the island to conduct research on species diversity, standing stock, species distribution, and oceanography. Plans were underway to find separate funding for the island outside of OCC. Possible funding sources included the National Science Foundation, rental of the island facilities to Canadians, funding from the Associated Students of OCC (ASOCC), and through other foundation grants and private donations. In March 2007, the Orange Coast College Foundation Board of Directors voted to sell the island after determining that keeping and maintaining it was unfeasible. As of July 2007, the island was in talks to be sold to a private party for $2.41 million. However, the sale did not materialize and the island was sold in March 2008 to a privately held Canadian corporation for $2.19 million. In 2015, a plan is in effect to remove the early Neutra buildings in the center of the campus and open up a large central park around which both the outlying 1970s buildings and several newer buildings will be clustered. In November 2016, an OCC student recorded a lecture by a professor of human sexuality, violating the school\'s Student Code of Conduct. In the lecture, the professor criticized President Donald Trump and Vice President Mike Pence, calling their election "an act of terrorism" against members of the LGBTQ community. The student shared the recording with a student club on campus, which then posted it on their public Facebook page. The video promptly went viral, sparking backlash and death threats against the professor. After an investigation, the student was suspended for one semester, and required to write an essay and apologize to the professor. After public outcry, the punishment was overturned in a special meeting of the Coast Community College District Board of Trustees, in the interest of bringing "closure to a chain of events that has led to the distress for many, most especially, an OCC teacher and student." In 2017, the professor was awarded the Faculty of the Year award by her peers, which she declined to accept and did not want to participate in related activities. The college is one of three in the Coast Community College District (CCCD) which also includes Golden West College in Huntington Beach, and Coastline Community College. CCCD is a regional organization providing administrative services and funding for post-secondary education. The district is chartered by the state of California to provide community college services. The mission of OCC is to provide inexpensive education in the trades, licensed trades and skilled professions, as well as remedial and transferable lower-division courses for students who plan to transfer to either a California State University or University of California campus. OCC is accredited by the Western Association of Schools and Colleges, Accrediting Commission for Community and Junior Colleges. It also has specialized accreditation by American Dental Association (Commission on Dental Accreditation), the American Dietetic Association (Commission on Accreditation for Dietetics Education), and the Joint Review Committee on Education in Radiologic Technology. Orange Coast College sponsors 25 sports programs. The 12 men\'s sports programs are baseball, basketball, crew, cross country, football, golf, soccer, swimming, tennis, track and field, volleyball and water polo. The 13 women\'s programs are cheerleading/dance, basketball, beach volleyball, crew, cross country, golf, soccer, softball, swimming, tennis, track and field, volleyball and water polo. LeBard Stadium is located on the campus. The Los Angeles Chargers have held training camp and regular season practices at the campus facilities. Coast Report has been OCC\'s campus newspaper since 1948. Coast Report is now an entirely digital news outlet. Orange Coast College\'s original design in the 1950s included a planetarium designed by Richard Neutra. Built in 1955, it featured a 24-foot dome and a Viewlex Apollo star projector, which was later donated to the Big Bear Planetarium Projector Museum. The theatre could accommodate 35 visitors. Because of the growth of the college and its astronomy program, the facility was unable to accommodate students. In 2012, a bond measure was passed to fundraise for a modern planetarium more than twice the size of the Neutra planetarium with seating for 129. Preservationists, led by Neutra\'s son Dion Neutra, fought to make the building and several others protected pieces of historical value. In 2015, the district approved a $450 million expansion that included the new planetarium. Construction commenced in 2016. In 2017, former professor Mary McChesney donated $1 million for a Foucault pendulum in the lobby. The lobby also has National Oceanic and Atmospheric Administration\'s display Science On a Sphere. The planetarium is used by the school\'s astronomy students and provides educational field trips to the area\'s grade schools. The planetarium opened in 2019 and is open to the general public. It was well received by the community. The facility hosts science, technology, engineering, and mathematics educational programs for kids and community telescope nights. During the school year, there are monthly guest lectures from astrophysicists, aeronautical scholars, and other space science experts called the "Skylark Speaker Series". Guests have included planetary scientist Konstantin Batygin, astrophysicist Sabrina Stierwalt, and aerospace engineer and Virgin Galactic Unity 25 crew member Christopher Huie. In 2021, they hosted a planetarium festival called "Dome Fest West", which used the domed theatre for immersive music experiences and laser shows. During the Solar eclipse of April 8, 2024, the college hosted a community education and viewing event that more than 3,000 people in the attended. The Orange County Register said it was one of the best planetariums they\'ve ever seen.'

In [43]:
txt_list = []
for idx in df.index:
    txt = "{}\n{}".format(df.loc[idx, "page_title"],
                          df.loc[idx, "ptag_text"])
    txt_list.append(txt)

In [38]:
txt = "\n\n".join(txt_list)

txt

r = "\[…]"

'Home Page - AACC\nSearch our Community College Finder Search upcoming AACC Events Search the AACC Member Directory Season 10, Episode 1: Talking to Pasco-Hernando State College about Cultural Change Through Listening, Learning and Acting AACC John E. Roueche Future Leaders Institute AACC Future Presidents Institute June 2-4, 2025 Washington, DC 2025 Presidents Academy Summer Institute July 12-15, 2025 The Ritz Carlton, Laguna Beach, CA The fourth edition of the Competencies is a fully comprehensive document to guide the development of employees dedicated to the community college mission, vision, and values. Buy now. ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nResearch - AACC\nCommunity colleges are centers of educational opportunity. They are an American invention that put publicly funded higher education at close-to-home facilities, beginning nearly 100 years ago with Joliet Junior College. Since then, community colleges have been inclusive institutions that welcome all who desire to learn, regardless of wealth, heritage, or previous academic experience. The process of making higher education available to the maximum number of people continues to evolve at 1,167 public and independent community colleges—1,600 when branch campuses are included. This section is your resource for community college statistics, historical information, and facts. The State of Community College Leadership: 2023 opens in a new windowDownload The State of Community College Leadership: 2023opens PDF file [PDF] The Economic Value of America’s Community Colleges Report This report assesses the impact of the increased alumni productivity of America’s community colleges1 on the national economy and the benefits generated by the colleges for students, taxpayers, and society. The results of this study show that America’s community colleges create a positive net impact on the U.S. economy and generate a positive return on investment for their main stakeholders. 1 For the purposes of this analysis, America’s community colleges are represented by the 1,071 degree-granting community colleges that reported their FY 2019-20 data to IPEDS. opens in a new windowCommunity college enrollment crisis? HISTORICAL TRENDS IN COMMUNITY COLLEGE ENROLLMENT opens in a new windowDownload the report.opens PDF file [PDF] Community college enrollment has been in decline nationally since peaking in 2010. This report will put the recent community college trends into perspective by reviewing community college enrollment from 2001 through 2017, and by examining concurrent trends that are related to community college enrollments. This report will provide the reader with a better understanding of enrollment changes for students with different characteristics (such as age, gender, or race and ethnicity) as well as by enrollment intensity. In addition, community college enrollment trends will be compared to other sectors of higher education. Furthermore, this report will examine enrollment trends in the context of other national, nonhigher education trends such as unemployment rates and high school graduation rates to better understand the trends we are seeing in community college enrollment. opens PDF file The Voluntary Framework of Accountability (VFA) is the principal institutional accountability and improvement framework for community colleges with measures defined to encompass the full breadth of the community college mission and the diversity of students’ goals and educational experiences. The American Association of Community Colleges (AACC) operates a web-based portal for community colleges to submit, analyze, and display their VFA data. In 2018, more than 200 colleges participated in the VFA. This document is intended to provide a sample of results from the 2018 collection cycle. opens in a new window opens in a new windowAACC CEO Survey: Compensation 2015opens PDF file (PDF) In 2015, the American Association of Community Colleges (AACC) conducted a survey of community college chief executive officers (CEOs) to collect their opinions on current issues, and gather information on their compensation. This report provides the results from this survey. Kent Phillippe Vice President, Research & Student Success Ph: 202.416.4505 kphillippe@aacc.nche.educreate new email ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nDataPoints: Number of HSIs drops - AACC\nFor the first time in 20 years, the number of Hispanic-serving institutions (HSIs) in the U.S. has decreased. It dropped by 10 institutions, from 569 in 2019-20 to 559 in 2020-21, according to analysis by Excelencia in Education. The decrease is due, in part, to enrollment declines, institutional closings and consolidation during the pandemic, the advocacy group said. HSIs are defined in federal legislation as having 25% or more undergraduate Hispanic student full-time equivalent enrollment. There was, however, significant growth among Emerging HSIs (eHSIs) — colleges approaching the 25% Latino student enrollment threshold — increasing by 31 institutions, from 362 to 393 over the same period. HSIs represent less than 20% of institutions but enroll two-thirds of all Latino undergraduates, according to Excelencia. Overall, almost 60% of HSIs are four-year institutions (public: 28%; private: 31%), and more than 40% (226 institutions) are two-year institutions (public: 40%; private: 1%). Among eHSIs, 70% are four-year institutions (private: 45%; public: 25%), and 30% are two-year institutions (public: 27%; private: 3%). The analysis is based on the most recent public data available from the U.S. Education Department’s National Center for Education Statistics for academic year 2020-21 – the first full academic year into the Covid pandemic. Filed Under: DataPoints, Diversity, Enrollment, News ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nHome Page - AACC\nSearch our Community College Finder Search upcoming AACC Events Search the AACC Member Directory Season 10, Episode 1: Talking to Pasco-Hernando State College about Cultural Change Through Listening, Learning and Acting AACC John E. Roueche Future Leaders Institute AACC Future Presidents Institute June 2-4, 2025 Washington, DC 2025 Presidents Academy Summer Institute July 12-15, 2025 The Ritz Carlton, Laguna Beach, CA The fourth edition of the Competencies is a fully comprehensive document to guide the development of employees dedicated to the community college mission, vision, and values. Buy now. ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nAACC John E. Roueche Future Leaders Institute - AACC\nThe AACC John E. Roueche Future Leaders Institute is a 3-day seminar designed for department chairs, deans, assistant/associate deans, or directors who look to advance into a senior leadership role. The Roueche – FLI will provide participants the opportunity to hone leadership skills and engage in a dialogue with experienced community college leaders and develop a network of colleagues from around the country. Details opens in a new windowAACC Competencies for Community College Leaders and the real-world illustrations that AACC believes are imperative to assist leaders in progressing along the leadership continuum provide the framework for the Roueche – FLI curriculum. The competencies focus areas are specific categories identified as having significance to the internal and external workings of the community college. The 9 focus areas are: The registration fee for the FLI is $1700 for employees of member colleges and $2000 for employees of non-member colleges. Fees include meals provided through the institute as well as institute materials. All fees must be paid prior to the start of the program. The John E. Roueche Future Leaders Institute Scholarship is named in honor of Dr. John E. Roueche, a nationally recognized authority in community college education. Dr. Roueche has played an important role in shaping community college leadership over the last 40 years. The John E. Roueche Legacy Fund will provide a $500 scholarship to support emerging leaders who have been accepted to participate in the Roueche-Future Leaders Institute but lack the financial resources to do so. This is a one-time $500 scholarship to be applied toward the Roueche-FLI registration fee only. This scholarship is non-transferrable. Submit a scholarship application: opens in a new windowJohn E. Roueche Future Leaders Institute. For more information, contact opens in a new windowaaccleadershipsuite@aacc.nche.educreate new email. opens in a new windowRegister now Tammy Reichelt Chief of Staff opens in a new windowtreichelt@aacc.nche.educreate new email June 2-4, 2025 Washington, D.C. The Royal Sonesta June 2-4, 2025 Washington, D.C. The Royal Sonesta ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\n2023 Outstanding Alumni Award Recipients - AACC\nWilliam A. Campbell, Sr., Economic Officer, U.S. Department of State Alumnus of Milwaukee Area Technical College (Wisconsin) Lanessa Owens-Chaplin, Civic Leader and Attorney, New York Civil Liberties Union Alumna of Onondaga Community College (New York) Meghan Maury, Senior Advisor for Data Policy, White House Office of Science and Technology Policy Alum of Holyoke Community College (Massachusetts) ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nnan\nFOR IMMEDIATE RELEASE April 29, 2025 Contact: Martha M. Parham, Ed.D. Cell: 714-932-3694 mparham@aacc.nche.edu Community college students will attend an Innovation Boot Camp to pitch their STEM solutions to real-world challenges Washington, DC – Today, the American Association of Community Colleges (AACC), in partnership with the National Science Foundation (NSF), announced that it has selected […] Filed Under: News, Press Release, Press Releases FOR IMMEDIATE RELEASE February 13, 2025 Contact: Martha M. Parham, Ed.D. Cell: 714-932-3694 mparham@aacc.nche.edu Washington, DC – After a storied career spanning more than five decades, American Association of Community Colleges (AACC) president and CEO, Walter G. Bumphus announced that he will be retiring at the end of the year. “On behalf of the board […] Filed Under: News, Press Release, Press Releases, Uncategorized FOR IMMEDIATE RELEASE January 21, 2025 Contact: Martha M. Parham, Ed.D. 202-728-0200 x209 mparham@aacc.nche.edu Community College Innovation Challenge invites community college students to create STEM solutions to real-world problems Washington, D.C. – Today, the American Association of Community Colleges (AACC) in partnership with the National Science Foundation (NSF), has launched its platform to advance student […] Filed Under: News, Press Release, Press Releases July 22, 2024 For Immediate Release Media Contacts: All Within My Hands Foundation Renee Richardson, Director of Philanthropy renee@allwithinmyhands.org (415) 458-1532 x10 American Association of Community Colleges Dr. Martha M. Parham, Sr. Vice President, Public Relations mparham@aacc.nche.edu (202) 728-0200 Year 6 is the largest grant to date with $2.6M committed, totaling more than $10M invested […] Filed Under: News, Press Release, Press Releases FOR IMMEDIATE RELEASE June 13, 2024 Contact: Martha M. Parham, Ed.D. Cell: 714-932-3694 mparham@aacc.nche.edu Perimeter College at Georgia State University; Dallas College; and County College of Morris took home winning titles following presentations of their STEM innovations to address real-world challenges Washington, DC – Today, the American Association of Community Colleges (AACC), in partnership with […] Filed Under: News, Press Release, Press Releases FOR IMMEDIATE RELEASE May 20, 2024 Contact: Martha M. Parham, Ed.D. Cell: 714-932-3694 mparham@aacc.nche.edu National initiative brings together two-year college professionals to advance their leadership skills and raise awareness of STEM technician education programs Washington, DC—The American Association of Community Colleges (AACC) announced an inaugural cohort for the ATE Future Leaders Fellows program with funding […] Filed Under: News, Press Release, Press Releases FOR IMMEDIATE RELEASE April 29, 2024 Contact: Martha M. Parham, Ed.D. Cell: 714-932-3694 mparham@aacc.nche.edu Community college students will attend an Innovation Boot Camp to pitch their STEM solutions to real-world challenges Washington, DC – Today, the American Association of Community Colleges (AACC), in partnership with the National Science Foundation (NSF), announced that it has selected […] Filed Under: News, Press Release, Press Releases FOR IMMEDIATE RELEASE January 22, 2024 Contact: Martha M. Parham, Ed.D. 202-728-0200 x209 mparham@aacc.nche.edu Community College Innovation Challenge invites community college students to create STEM solutions to real-world problems Washington, D.C. – Today, the American Association of Community Colleges (AACC) in partnership with the National Science Foundation (NSF), has launched its platform to advance student […] Filed Under: News, Press Release, Press Releases December 7, 2023 Media Contact: Dr. Martha Parham, Sr. Vice President, Public Relations mparham@aacc.nche.edu 202-728-0200 For Immediate Release Tulsa Community College’s Holistic Approach to the Development of Social Capital By Leigh Goodson, President and CEO Tulsa Community College Community colleges embrace students from all walks of life. In Fall 2022, 27% of students at Tulsa […] Filed Under: News, Press Release, Press Releases December 7, 2023 Media Contact: Dr. Martha Parham, Sr. Vice President, Public Relations mparham@aacc.nche.edu 202-728-0200 For Immediate Release Wisconsin College breaks student barriers as global leader of OER Dr. Sunem Beaton-Garcia, President Opinion Editorial As the President of Chippewa Valley Technical College (CVTC) in west-central Wisconsin, I have the privilege of witnessing the transformative power […] Filed Under: News, Press Release, Press Releases ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nAACC Annual - AACC\nSince 1920, the American Association of Community Colleges (AACC) has been the go-to organization for the nation’s predominately associate degree-granting regionally accredited institutions. The association hosts one of the largest convenings of community college professionals and offers engaging speakers, relevant professional development, and unsurpassed networking opportunities. AACC Annual provides access to the nation’s community college leaders who collectively serve more than 40 percent of the nation’s undergraduates. AACC Annual creates opportunities to design and solve today’s priority challenges and to identify opportunities and innovation to support the country’s community college students. AACC 2026 April 11 – 14 Seattle, Washington (must pay at the time of registration to lock in the early bird rate) (AACC will not change the speaker list after this deadline) (AACC will not honor the speaker registration rate after this deadline passes) (Balance must be paid on this date, or registration will move to late registration rates) (must pay at the time of registration to lock in the early bird rate) (Registration will not reopen. Tickets will not be available for purchase after this date) You must register for virtual orientation through the registration form. Looking for information about the 98th Annual Convention? Search the opens in a new window program guide. Dr. Angel M. Royal Senior Vice President, Strategic Initiatives Ph: 202.728.0200 x255 aroyal@aacc.nche.edu create new email ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nContacts - AACC\nTammy Reichelt — treichelt@aacc.nche.edu Amy Bortmes — abortmes@aacc.nche.edu Questions regarding specific commission meetings should be directed to the appropriate commission staff liaison. ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nAdvisory Board Members - AACC\nJen Worth Senior Vice President, Academic & Workforce Development Ph: 202.728.0200 x276 jworth@aacc.nche.edu ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nnan\nUsername or Email Address Remember Me Register | Lost your password? ← Go to AACC\n\nStudent Aid Alliance Urges Congress to Continue Supporting Student Aid Programs, Double Pell Grants - AACC\nStudent Aid Alliance Urges Congress to Continue Supporting Student Aid Programs, Double Pell Grants”>Student Aid Alliance Urges Congress to Continue Supporting Student Aid Programs, Double Pell Grants (PDF) Filed Under: OGR Letters, OGR Letters Budget & Appropriations ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nReports - AACC\nWomen in Community College Leadership Report (2024) Download the report. Over 36.6 percent of community college presidents are women (Philippe, 2023). The data in this infographic provide an overall summary of the key statistics on the role, background, application process, transitioning, and future movement of women community college presidents using data from the American Council on Education’s American College President Study (Melidona et al., 2023). The State of Community College Leadership: 2023 Download The State of Community College Leadership: 2023 [PDF] VIRTUAL LISTENING TOUR REPORT 2022 Snapshot of Resilience and Excellence Download the report. A new American Association of Community Colleges (AACC) report summarizes the challenges that community colleges faced during the Covid pandemic as well as their responses. It covers a broad area, including enrollment declines, the equity agendas, pandemic excellence and partnerships, and the changing landscape and competition. ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nDataPoints: Prepared for the workforce - AACC\nTechnical career students most strongly feel that their education prepared them for their jobs. Read full PDF. Filed Under: DataPoints, Workforce ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nBudget and Appropriations - AACC\nAACC’s Office of Government Relations (OGR) advocates for robust increases to key community college programs as part of the annual budget and appropriations process. These include the Pell Grant program, campus-based aid programs, institutional aid programs, and key workforce development programs. Washington Watch: Budget & Appropriations David Baime Senior Vice President, Government Relations Ph: 202.728.0200 x224 dbaime@aacc.nche.edu Jim Hermes Associate Vice President, Government Relations Ph: 202.728.0200 x216 jhermes@aacc.nche.edu Kathryn Gimborys Manager, Government Relations Ph: 202.728.0200 x258 kgimborys@aacc.nche.edu ©2025 American Association of Community Colleges One Dupont Circle, NW, Suite 700 Washington, DC 20036\n\nDataPoints - AACC\nTotal state support for higher education increased by 4.3% for fiscal year 2025, based on data recently released by the State Higher Education Executive Officers Association (SHEEO) in its annual Grapevine report. However, after adjusting for the effects of inflation, the increase was a more modest 1.3%. The level of support from FY 2019 (prior to the pandemic) to FY 2025 increased 38% (See Figure 1). Even after adjusting for inflation, state support increased by 9.4% across that time. Figure 1 demonstrates the impact that Covid had on the level of state support for higher education for FY 2021, where support decreased nearly 1% from FY 2020 to FY 2021 after adjusting for inflation. While the overall trend for s

In [39]:
len(txt)

1349884